<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="login-container">
        <form action="check" method="POST">
            Username <input type="text" class="textfield" name="username" placeholder="Username"/><br>
            Password <input type="password" class="textfield" name="password" placeholder="Password"/><br>
            <input type="submit" class="btn-submit" value="Login">
        </form>
    </div>
</body>

<style>
    .login-container {
        width: 100%;
        height: 100vh;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .login-container form {
        width: 300px;
        height: 300px;
        background-color: #ccc;
        display: inline-flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }

    .login-container form input {
        margin: 10px;
    }

    .btn-submit {
        width: 100px;
        height: 30px;
        background-color: #000;
        color: #fff;
        border: none;
        border-radius: 5px;
    }

    .textfield {
        width: 200px;
        height: 30px;
        border-radius: 5px;
    }
</style>

</html>