<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <?php
    $_SESSION['loginUser'] = NULL;
    ?>

    <?php
    $loginForm = $this->form;
    $username = $form->get('username');
    $password = $form->get('password');
    $loginSubmit = $form->get('submit');
    ?>
    <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-md-offset-3">
            <?= $this->form()->openTag($loginForm); ?>
            <?= $this->formRow($username); ?>
            <?= $this->formRow($password); ?>
            <?= $this->formRow($loginSubmit); ?>
            <?= $this->form()->closeTag($loginForm); ?>
        </div>
    </div>
</body>

</html>