<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <?php
        if ($_SESSION['loginUser'] == NULL || $_SESSION['loginUser']->getRole() != "MN") {
          header("Location: http://localhost/smartradio/login/login ");
          die();
        }else{
          echo ("<h1>Welcome {$_SESSION['loginUser']->getUserName()} .</h1>");  
        }
    ?>
</body>
</html>