<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <?php
        if (isset($_SESSION['msg']) && isset($_SESSION['role'])) {
            if ($_SESSION['role'] == "AD") {
              header("Location: http://localhost/smartradio/login/login ");
              die();
            } else {
              echo ("<h1>Welcome {$_SESSION['msg']} .</h1>");
            }
          }
    ?>
</body>
</html>