<?= $this->doctype() ?>

<html lang="en">

<head>
    <meta charset="utf-8">

    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css'/>
        <link rel=" stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

    <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . 'public/img/favicon.ico'])
        ->prependStylesheet($this->basePath('public/css/style.css'))
        ->prependStylesheet($this->basePath('public/css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('public/plugins/fontawesome-free/css/all.min.css'))

        ->prependStylesheet($this->basePath('public/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css'))
        ->prependStylesheet($this->basePath('public/plugins/icheck-bootstrap/icheck-bootstrap.min.css'))
        ->prependStylesheet($this->basePath('public/plugins/jqvmap/jqvmap.min.css'))
        ->prependStylesheet($this->basePath('public/dist/css/adminlte.css'))
        ->prependStylesheet($this->basePath('public/plugins/overlayScrollbars/css/OverlayScrollbars.min.css'))
        ->prependStylesheet($this->basePath('public/plugins/daterangepicker/daterangepicker.css'))
        ->prependStylesheet($this->basePath('public/plugins/summernote/summernote-bs4.min.css'))
    ?>

    <?= $this->inlineScript()
        ->prependFile($this->basePath('public/js/bootstrap.min.js'))
        ->prependFile($this->basePath('public/js/jquery-3.3.1.min.js'))
    ?>
    <style>
        .navbar-badge{
            font-size: 50% !important;
        }
    </style>
</head>

<body>

    <div class="container">
        <?= $this->content ?>

    </div>
    <script src="../public/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="../public/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    
    <!-- Bootstrap 4 -->
    <script src="../public/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="../public/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="../public/plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="../public/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="../public/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="../public/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="../public/plugins/moment/moment.min.js"></script>
    <script src="../public/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="../public/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="../public/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="../public/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="../public/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="../public/dist/js/demo.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="../public/dist/js/pages/dashboard.js"></script>

</body>

</html>